# Run unit tests for your Python application
---
name: C4W3-Ungraded-Lab

# Controls when the action will run.
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'course4/week3-ungraded-labs/C4_W3_Lab_4_Github_Actions/**'
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, reopened, edited, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: course4/week3-ungraded-labs/C4_W3_Lab_4_Github_Actions/

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          cd app/
          pytest
