---
  name: module4_task2
  
  on:
    push:
      branches:
        - main
        - master
        # https://www.freeformatter.com/cron-expression-generator-quartz.html
    schedule:
      - cron: "0 0 * * *"
        # https://frontside.com/blog/2020-05-26-github-actions-pull_request/
    pull_request:
      types: [opened, reopened, edited, ready_for_review]
  jobs:
    build:
      name: Build job
      runs-on: ubuntu-22.04
  
      steps:
        - uses: actions/checkout@v3
        - name: Setup Hugo
          run: |
            ./setup.sh
            export PATH="$PATH:/usr/bin/gcc"
            echo "Updated PATH: $PATH"
          working-directory: module4_task2
        - name: Validate Makefile execution
          run: |
            make help
            make build-docker
            docker images
            sudo systemctl restart docker
            sudo chmod 777 /var/run/docker.sock
            ls -l /var/run/docker.sock
            make docker-tests
            make build
            make lint
            make run
            which gcc
            make unit-tests
            make integration-tests
            make package
            make clean
          working-directory: module4_task2
        - name: clean
          run: make clean
          working-directory: module4_task2
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: 1.0.1
            files: |
                  module4_task0/awesome-website.zip
                  module4_task0/DEPLOY.md
        - name: archive build
          if: ${{ success()}}
          uses: actions/upload-artifact@v3
          with:
            name: upload-package
            path: module4_task2/awesome-website.zip